# -*- coding: utf-8 -*-
"""Project VN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17P_KsZi9HzoV5ZYD2hE8GyfzjbZyn1Oe
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("PJM_Load_hourly.csv")

df['Datetime'] = pd.to_datetime(df['Datetime'])
df = df.set_index("Datetime")

col = df.select_dtypes(include=['float64', 'int64']).columns[0]
df = df[[col]].rename(columns={col: "load"})
df = df.resample("H").mean().interpolate()

df["theta_1"] = df["load"].shift(1)
df["theta_2"] = df["load"].shift(24)
df["theta_3"] = df["load"].shift(168)
df = df.dropna()

train_size = int(len(df)*0.8)
train = df.iloc[:train_size]
test  = df.iloc[train_size:]

def metrics(y_true, y_pred):
    MAE  = mean_absolute_error(y_true, y_pred)
    RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
    MAPE = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    return MAE, RMSE, MAPE

har_model = ARIMA(y_train, exog=X_train, order=(1,0,1))
har_res = har_model.fit()

har_pred = har_res.predict(start=y_test.index[0], end=y_test.index[-1], exog=X_test)

import seaborn as sns
import matplotlib.pyplot as plt

# Combine actual & predicted into one dataframe
viz_df = pd.DataFrame({
    "Actual": y_test,
    "Predicted": har_pred
})

plt.figure(figsize=(12,6))
sns.lineplot(data=viz_df)
plt.title("HAR-ARIMA: Actual vs Predicted")
plt.xlabel("Time")
plt.ylabel("Values")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7,6))
sns.scatterplot(x=y_test, y=har_pred)
plt.title("Actual vs Predicted (HAR-ARIMA)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.grid(True)
plt.show()

har_mae, har_rmse, har_mape = metrics(y_test, har_pred)
print("\n HAR-ARIMA PERFORMANCE ")
print(f"MAE  : {har_mae:.3f}")
print(f"RMSE : {har_rmse:.3f}")
print(f"MAPE : {har_mape:.2f}%")

sarima_model = SARIMAX(y_train, order=(1,0,1), seasonal_order=(1,0,1,24))
sarima_res = sarima_model.fit()

import seaborn as sns
import matplotlib.pyplot as plt

# --- SARIMA Prediction ---
sarima_pred = sarima_res.predict(start=y_test.index[0],
                                 end=y_test.index[-1])

# --- Combine into dataframe ---
sarima_viz = pd.DataFrame({
    "Actual": y_test,
    "Predicted": sarima_pred
})

# --- Line Plot ---
plt.figure(figsize=(12,6))
sns.lineplot(data=sarima_viz)
plt.title("SARIMA: Actual vs Predicted")
plt.xlabel("Time")
plt.ylabel("Values")
plt.grid(True)
plt.tight_layout()
plt.show()

sarima_err = y_test - sarima_pred

plt.figure(figsize=(10,5))
sns.histplot(sarima_err, kde=True)
plt.title("SARIMA Error Distribution")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

sarima_mae, sarima_rmse, sarima_mape = metrics(y_test, sarima_pred)
print("\n BASELINE SARIMA PERFORMANCE ")
print(f"MAE  : {sarima_mae:.3f}")
print(f"RMSE : {sarima_rmse:.3f}")
print(f"MAPE : {sarima_mape:.2f}%")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

xgb_model = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror"
)

xgb_model.fit(X_train_scaled, y_train)
xgb_pred = xgb_model.predict(X_test_scaled)

xgb_mae, xgb_rmse, xgb_mape = metrics(y_test, xgb_pred)
print("\n XGBOOST BASELINE PERFORMANCE")
print(f"MAE  : {xgb_mae:.3f}")
print(f"RMSE : {xgb_rmse:.3f}")
print(f"MAPE : {xgb_mape:.2f}%")

import seaborn as sns
import matplotlib.pyplot as plt

# Combine actual and predicted values
xgb_viz = pd.DataFrame({
    "Actual": y_test,
    "Predicted": xgb_pred
})

# Line plot
plt.figure(figsize=(12,6))
sns.lineplot(data=xgb_viz)
plt.title("XGBoost Regressor: Actual vs Predicted")
plt.xlabel("Time")
plt.ylabel("Values")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7,6))
sns.scatterplot(x=y_test, y=xgb_pred)
plt.title("Actual vs Predicted (XGBoost Regressor)")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.grid(True)
plt.show()

summary = pd.DataFrame({
    "Model": ["SARIMA", "HAR-ARIMA", "XGBoost"],
    "MAE": [sarima_mae, har_mae, xgb_mae],
    "RMSE": [sarima_rmse, har_rmse, xgb_rmse],
    "MAPE%": [sarima_mape, har_mape, xgb_mape]
})

print("\n\n FINAL MODEL COMPARISON TABLE \n")
print(summary.to_string(index=False))

